version: '3'

services:
  server:
    build: .
    command: 'npm start'
    ports:
      - '3000:3000'
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/src:z

  db:
    image: 'mongo'
    container_name: mongo
    ports:
      - '27017:27017'
    command: --quiet
    volumes:
      - ./data/db:/data/db:z
      
    mongodb://ADMIN:123456@127.0.0.1:27017/eleazar
